name: main

on: [push, pull_request]
jobs:
  golang-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go test ./... -tags=unit
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - uses: actions/checkout@v3
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.2"
        install-go: false
  security-scanning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: securego/gosec@master
      with:
        args: ./...
  release:
    needs: [golang-ci, unit-tests, code-quality, security-scanning]
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
    - uses: actions/checkout@master
    - uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19
        branch: main
        extra_plugins: |
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
